### PR TITLE
Update 61-openmediavault-dev-disk-by-id.rules

### PR DESCRIPTION
**Pull request by maxfb87**
Add Genesys USB2.0/SATA adapter to avoid the problem explained in  #746 PR.

Fixes: [#1229]

Signed-off-by: Max Faber maxfb87@yahoo.it

- [x] References issue
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Review by votdev — APPROVED** [review]

**Comment by votdev** [comment]
Only one thing, can you please add the [Signed-off-by](https://openmediavault.readthedocs.io/en/5.x/development/contribute.html#contribution-rules) line in the commit message?

**Comment by maxfb87** [comment]
> Only one thing, can you please add the [Signed-off-by](https://openmediavault.readthedocs.io/en/5.x/development/contribute.html#contribution-rules) line in the commit message?

Done! :-)

**Comment by votdev** [comment]
> > Only one thing, can you please add the [Signed-off-by](https://openmediavault.readthedocs.io/en/5.x/development/contribute.html#contribution-rules) line in the commit message?
> 
> Done! :-)

Hmm, not really. You added it to the comment above, but it must be added to the [commit message](https://github.com/openmediavault/openmediavault/pull/1233/commits/fbd7639034cad294393b0b8aa22dad5ee08867ae). Check https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message for more information.
Sorry for that effort, but the signed-off-by must be stored in the git repository and not only here on the GitHub page.

**Comment by maxfb87** [comment]
> > > Only one thing, can you please add the [Signed-off-by](https://openmediavault.readthedocs.io/en/5.x/development/contribute.html#contribution-rules) line in the commit message?
> > 
> > 
> > Done! :-)
> 
> Hmm, not really. You added it to the comment above, but it must be added to the [commit message](https://github.com/openmediavault/openmediavault/pull/1233/commits/fbd7639034cad294393b0b8aa22dad5ee08867ae). Check https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message for more information. Sorry for that effort, but the signed-off-by must be stored in the git repository and not only here on the GitHub page.

Ook, now a i think it's ok, please tell me if it isn't.
Thanks also for helping

**Pull request merged**
