### PR TITLE
Improve ECDH key exchange in WebGUI

### PR DESCRIPTION
**Pull request by jannispinter**
I would suggest to prefer X25519 over NIST curves here and set NIST P-384 as fallback.

### CODE REVIEW

**Comment by votdev** [comment]
Please rebase branch

**Comment by jannispinter** [comment]
I've merged openmediavault/master with patch-2 branch, not sure if it is alright yet though

**Comment by votdev** [comment]
> I've merged openmediavault/master with patch-2 branch, not sure if it is alright yet though

No, that not right. You need to rebase your branch. Currently your PR contains 2 commits, but only one is necessary.

Please also follow the section ``Code contributions`` in https://openmediavault.readthedocs.io/en/latest/development/contribute.html#. Forgot to check that in your previous PR.

**Comment by jannispinter** [comment]
Thank you! I will open up a new PR from a rebased branch.

**Pull request closed without merging**
