### PR TITLE
add base path option to wetty

### PR DESCRIPTION
**Pull request by EmTeedee**
Fixes: #1410

Built and tested.
When using a reverse-proxy setup the "Open UI" button might not work, depending on hostname and port of the proxy. To address that, one would need an extra option for that just for this one button.

- [x] References issue
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by votdev** [comment]
Please introduce a new environment variable Adding such an option in the UI breaks the philosophy of OMV.

**Comment by votdev** [comment]
> When using a reverse-proxy setup the "Open UI" button might not work, depending on hostname and port of the proxy. To address that, one would need an extra option for that just for this one button.

That might be a problem if there is an environment variable used. But TBH, this is a special edge case which is not the main purpose of OMV. I say it as often as needed, OMV is no Webmin where the UI provides whatever possible option is available for a service.

**Review by votdev — CHANGES_REQUESTED** [review]
Isn't that doable via path rewriting rules in the proxy?

**Comment by EmTeedee** [comment]
Wetty provides the base option to address the problem, if openmediavault has something similar, I haven't found it.

**Comment by votdev** [comment]
> Wetty provides the base option to address the problem, if openmediavault has something similar, I haven't found it.

That's because Angular sets that during compilation and changing `<base>` tag at runtime is a little bit hackish.

**Pull request merged**
