### PR TITLE
Issue #1690: Replace hdparm with smartctl for better hardware support

### PR DESCRIPTION
**Pull request by votdev**
Fixes: https://github.com/openmediavault/openmediavault/issues/1690

### CODE REVIEW

**Comment by votdev** [comment]
@ryecoaaron Could you please do some tests with real hardware and report your experiences?

**Comment by ryecoaaron** [comment]
> @ryecoaaron Could you please do some tests with real hardware and report your experiences?

I can when I get back home in a few days.

**Comment by ryecoaaron** [comment]
The status is unknown for all drives but looking at Details for each drive is working.

**Comment by votdev** [comment]
> The status is unknown for all drives but looking at Details for each drive is working. image

Too bad, i think this is related to https://github.com/openmediavault/openmediavault/pull/1693.

**Pull request merged**
