### PR TITLE
Add `image` datatable column

### PR DESCRIPTION
**Pull request by votdev**
Example:
```
{
    name: gettext('QR Code'),
    flexGrow: 3,
    cellTemplateName: 'image',
    cellTemplateConfig: {
        class: 'omv-max-w-100',
		src: 'download.php?service=Rrd&method=getGraph&params={"kind":"cpu-0","period":"hour"}'
    }
},
```
[Example.webm](https://github.com/openmediavault/openmediavault/assets/1897962/f6bd1c54-e605-430a-846e-9918b4679780)

More Examples:

Use the property `name` of the row data to render the URL.
```
{
    name: gettext('QR Code'),
    flexGrow: 3,
    cellTemplateName: 'image',
    cellTemplateConfig: {
        class: 'omv-max-w-100',
        src: 'download.php?service=Foo&method=getImage&params={"name":"{{ name }}"}'
    }
},
```

Use the property `img_src` of the row data to render the URL.
```
{
    name: gettext('QR Code'),
    flexGrow: 3,
    cellTemplateName: 'image',
    cellTemplateConfig: {
        class: 'omv-max-w-100',
        src: '{{ img_src }}'
    }
},
```

Use base64 encoded data:
```
{
  name: gettext('QR Code'),
  flexGrow: 3,
  cellTemplateName: 'image',
  cellTemplateConfig: {
    alt: "test",
    src: "data:image/x-icon;base64,AAACAAEAICAAAAoACgCoEAAAFgAAACgAAAAgAAAAQAAAAAEAIAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEIAP8RCAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEQgA/xEIAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP8iIt3/IiLd/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/yIi3f8iIt3/AAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/yIi3f8iIt3/IiLd/yIi3f/Mu6r/zLuq/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/IiLd/yIi3f8iIt3/IiLd/8y7qv/Mu6r/AAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/IiLd/yIi3f8iIt3/IiLd/8y7qv/Mu6r/AAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP8iIt3/IiLd/yIi3f8iIt3/zLuq/8y7qv8AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP8AAAD/AAAA/wAAAAAAAAAAAAAA/wAAAP8iIt3/IiLd/yIi3f8iIt3/zLuq/8y7qv8AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/wAAAP8AAAD/AAAAAAAAAAAAAAD/AAAA/yIi3f8iIt3/IiLd/yIi3f/Mu6r/zLuq/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/yIi3f8iIt3/IiLd/yIi3f8AAAD/AAAA/yIi3f8iIt3/IiLd/yIi3f/Mu6r/zLuq/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/IiLd/yIi3f8iIt3/IiLd/wAAAP8AAAD/IiLd/yIi3f8iIt3/IiLd/8y7qv/Mu6r/AAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP8iIt3/IiLd/yIi3f8iIt3/IiLd/yIi3f8iIt3/IiLd/8y7qv/Mu6r/AAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/yIi3f8iIt3/IiLd/yIi3f8iIt3/IiLd/yIi3f8iIt3/zLuq/8y7qv8AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/IiLd/yIi3f8iIt3/IiLd/yIi3f8iIt3/zLuq/8y7qv8AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP8iIt3/IiLd/yIi3f8iIt3/IiLd/yIi3f/Mu6r/zLuq/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/yIi3f8iIt3/IiLd/yIi3f8iIt3/IiLd/yIi3f8iIt3/zLuq/8y7qv8AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/IiLd/yIi3f8iIt3/IiLd/yIi3f8iIt3/IiLd/yIi3f/Mu6r/zLuq/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP/Mu6r/zLuq/8y7qv/Mu6r/zLuq/8y7qv/Mu6r/zLuq/8y7qv/Mu6r/AAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/8y7qv/Mu6r/zLuq/8y7qv/Mu6r/zLuq/8y7qv/Mu6r/zLuq/8y7qv8AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////z////8////8D////A////AD///wA///wA///8AP/8MAP//DAD//AAD//wAA//8AA///AAP//wAP//8AD///AAP//wAD//8AA///AAP//wAP//8AD//////////////////////////////////////////////////////8="
  }
},
```

- [ ] References issue
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Review by ryecoaaron — APPROVED** [review]
That would be very useful and I like how you implemented it.

**Comment by ryecoaaron** [comment]
if we could use a base64 encoded image directly from the OMV database, that would be great.  I'm fine writing php otherwise to return the base64 string if the column supports it.

**Comment by votdev** [comment]
> if we could use a base64 encoded image directly from the OMV database, that would be great. I'm fine writing php otherwise to return the base64 string if the column supports it.

Could you please explain more detailed what you are thinking of here?

I think the RPC which is responsible for fetching the data to be displayed in the datatable can simply read the file content of the image, encode it with base64 and then adds it as a property to the row properties.

**Comment by ryecoaaron** [comment]
> I think the RPC which is responsible for fetching the data to be displayed in the datatable can simply read the file content of the image, encode it with base64 and then adds it as a property to the row properties.

If this is the case, then we are good.  I just had thought about base64 encoding images and storing them in the database to be viewed in the datatable.  This would avoid having to store image files in the filesystem.

**Comment by votdev** [comment]
> > I think the RPC which is responsible for fetching the data to be displayed in the datatable can simply read the file content of the image, encode it with base64 and then adds it as a property to the row properties.
> 
> If this is the case, then we are good. I just had thought about base64 encoding images and storing them in the database to be viewed in the datatable. This would avoid having to store image files in the filesystem.

Storing them in the database should not be a problem because it is a string. But i will think about if it makes sense to add a validator and special `base64` type in the database spec.

**Comment by votdev** [comment]
@ryecoaaron Please note the changes done by https://github.com/openmediavault/openmediavault/commit/0edd54fb8912242a93f41e28df1c9d0139d2b731. This way the `image` column can be used without the need of the `cellTemplateConfig.src` property. Configure the `prop` field as usual to tell the column where the data to be displayed comes from. Then deliver the base64 encoded image data as dedicated property in the row data.

```
{
    name: gettext('QR Code'),
    flexGrow: 1,
    prop: 'foo',
    cellTemplateName: 'image'
},
```

**Comment by ryecoaaron** [comment]
It works great!  Thanks.
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-wireguard/commit/2120190ed1ac953d6970c420838b9ffa92bdeb42

**Pull request merged**
