### PR TITLE
 Fix spelling in German translation 

### PR DESCRIPTION
**Pull request by jochenberger**

### CODE REVIEW

**Comment by jochenberger** [comment]
Sorry, I'm not going through the effort of signing a CLA for a trivial one-line non-code translation fix. Please don't make it unnecessarily hard to contribute.

**Comment by votdev** [comment]
CLA's are really important nowadays, please see the [OMV docs](https://openmediavault.readthedocs.io/en/latest/development/contribute.html) for references.

A really good example why CLA is so necessary is this [article](https://www.golem.de/news/programmierer-wenn-der-urheber-gegen-das-urheberrecht-verliert-1904-140463-3.html) (German).

**Comment by votdev** [comment]
I will close this issue because translations must be done here: https://translate.openmediavault.org

**Comment by jochenberger** [comment]
> CLA's are really important nowadays, please see the [OMV docs](https://openmediavault.readthedocs.io/en/latest/development/contribute.html) for references.

Yes. For non-trivial code changes, which this isn't - in two ways. IMHO, for changes like this, they are just standing in the way.

**Pull request closed without merging**
