### PR TITLE
UDEV rules must be more restrictive to only apply to disk devices

### PR DESCRIPTION
**Pull request by votdev**
Fixes: https://github.com/openmediavault/openmediavault/issues/842

Signed-off-by: Volker Theile <votdev@gmx.de>

- [x] References issue
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by votdev** [comment]
Requested some more reviews in the [forum](https://forum.openmediavault.org/index.php?thread/32184-rpi4-quad-says-hat/&postID=255980#post255980).

**Comment by votdev** [comment]
```
root@orangepipc2:~# udevadm info --query=property --name=/dev/sda --attribute-walk

Udevadm info starts with the device specified by the devpath and then
walks up the chain of parent devices. It prints for every device
found, all possible attributes in the udev rules key format.
A rule to match, can be composed by the attributes of the device
and the attributes from one single parent device.

  looking at device '/devices/platform/soc/1c1b000.usb/usb3/3-1/3-1:1.0/host0/target0:0:0/0:0:0:0/block/sda':
    KERNEL=="sda"
    SUBSYSTEM=="block"
    DRIVER==""
    ATTR{capability}=="50"
    ATTR{events}==""
    ATTR{stat}=="    2691        3   146396     9778        2        0       16        2        0     7612     9780        0        0        0        0        0        0"
    ATTR{size}=="976773168"
    ATTR{ro}=="0"
    ATTR{events_async}==""
    ATTR{discard_alignment}=="0"
    ATTR{hidden}=="0"
    ATTR{removable}=="0"
    ATTR{ext_range}=="256"
    ATTR{alignment_offset}=="0"
    ATTR{range}=="16"
    ATTR{events_poll_msecs}=="-1"
    ATTR{inflight}=="       0        0"

  looking at parent device '/devices/platform/soc/1c1b000.usb/usb3/3-1/3-1:1.0/host0/target0:0:0/0:0:0:0':
    KERNELS=="0:0:0:0"
    SUBSYSTEMS=="scsi"
    DRIVERS=="sd"
    ATTRS{evt_inquiry_change_reported}=="0"
    ATTRS{type}=="0"
    ATTRS{model}=="00AAKB-00H8A0   "
    ATTRS{state}=="running"
    ATTRS{queue_type}=="none"
    ATTRS{max_sectors}=="240"
    ATTRS{iocounterbits}=="32"
    ATTRS{iodone_cnt}=="0xc72"
    ATTRS{inquiry}==""
    ATTRS{evt_media_change}=="0"
    ATTRS{evt_capacity_change_reported}=="0"
    ATTRS{scsi_level}=="6"
    ATTRS{evt_soft_threshold_reached}=="0"
    ATTRS{evt_lun_change_reported}=="0"
    ATTRS{blacklist}==""
    ATTRS{iorequest_cnt}=="0xc72"
    ATTRS{queue_depth}=="1"
    ATTRS{vendor}=="WDC WD50"
    ATTRS{evt_mode_parameter_change_reported}=="0"
    ATTRS{eh_timeout}=="10"
    ATTRS{device_blocked}=="0"
    ATTRS{rev}=="    "
    ATTRS{ioerr_cnt}=="0x2"
    ATTRS{timeout}=="30"
    ATTRS{device_busy}=="0"

  looking at parent device '/devices/platform/soc/1c1b000.usb/usb3/3-1/3-1:1.0/host0/target0:0:0':
    KERNELS=="target0:0:0"
    SUBSYSTEMS=="scsi"
    DRIVERS==""

  looking at parent device '/devices/platform/soc/1c1b000.usb/usb3/3-1/3-1:1.0/host0':
    KERNELS=="host0"
    SUBSYSTEMS=="scsi"
    DRIVERS==""

  looking at parent device '/devices/platform/soc/1c1b000.usb/usb3/3-1/3-1:1.0':
    KERNELS=="3-1:1.0"
    SUBSYSTEMS=="usb"
    DRIVERS=="usb-storage"
    ATTRS{authorized}=="1"
    ATTRS{supports_autosuspend}=="1"
    ATTRS{interface}=="MSC Bulk-Only Transfer"
    ATTRS{bInterfaceNumber}=="00"
    ATTRS{bAlternateSetting}==" 0"
    ATTRS{bInterfaceSubClass}=="06"
    ATTRS{bInterfaceProtocol}=="50"
    ATTRS{bNumEndpoints}=="02"
    ATTRS{bInterfaceClass}=="08"

  looking at parent device '/devices/platform/soc/1c1b000.usb/usb3/3-1':
    KERNELS=="3-1"
    SUBSYSTEMS=="usb"
    DRIVERS=="usb"
    ATTRS{bcdDevice}=="0100"
    ATTRS{devpath}=="1"
    ATTRS{tx_lanes}=="1"
    ATTRS{speed}=="480"
    ATTRS{bDeviceSubClass}=="00"
    ATTRS{version}==" 2.00"
    ATTRS{idProduct}=="2338"
    ATTRS{serial}=="7D5000AA5B50"
    ATTRS{rx_lanes}=="1"
    ATTRS{avoid_reset_quirk}=="0"
    ATTRS{bDeviceClass}=="00"
    ATTRS{configuration}=="USB Mass Storage"
    ATTRS{bDeviceProtocol}=="00"
    ATTRS{bNumInterfaces}==" 1"
    ATTRS{maxchild}=="0"
    ATTRS{removable}=="unknown"
    ATTRS{authorized}=="1"
    ATTRS{bmAttributes}=="c0"
    ATTRS{devspec}=="(null)"
    ATTRS{busnum}=="3"
    ATTRS{idVendor}=="152d"
    ATTRS{bConfigurationValue}=="1"
    ATTRS{devnum}=="2"
    ATTRS{bMaxPower}=="2mA"
    ATTRS{bNumConfigurations}=="1"
    ATTRS{manufacturer}=="JMicron"
    ATTRS{product}=="USB to ATA/ATAPI bridge"
    ATTRS{ltm_capable}=="no"
    ATTRS{bMaxPacketSize0}=="64"
    ATTRS{urbnum}=="9603"
    ATTRS{quirks}=="0x0"

  looking at parent device '/devices/platform/soc/1c1b000.usb/usb3':
    KERNELS=="usb3"
    SUBSYSTEMS=="usb"
    DRIVERS=="usb"
    ATTRS{version}==" 2.00"
    ATTRS{bMaxPower}=="0mA"
    ATTRS{manufacturer}=="Linux 5.8.16-sunxi64 ehci_hcd"
    ATTRS{bmAttributes}=="e0"
    ATTRS{authorized}=="1"
    ATTRS{urbnum}=="28"
    ATTRS{devnum}=="1"
    ATTRS{idVendor}=="1d6b"
    ATTRS{bNumInterfaces}==" 1"
    ATTRS{bDeviceProtocol}=="00"
    ATTRS{rx_lanes}=="1"
    ATTRS{product}=="EHCI Host Controller"
    ATTRS{idProduct}=="0002"
    ATTRS{serial}=="1c1b000.usb"
    ATTRS{avoid_reset_quirk}=="0"
    ATTRS{interface_authorized_default}=="1"
    ATTRS{tx_lanes}=="1"
    ATTRS{removable}=="unknown"
    ATTRS{maxchild}=="1"
    ATTRS{devpath}=="0"
    ATTRS{bConfigurationValue}=="1"
    ATTRS{quirks}=="0x0"
    ATTRS{authorized_default}=="1"
    ATTRS{bDeviceSubClass}=="00"
    ATTRS{bNumConfigurations}=="1"
    ATTRS{bcdDevice}=="0508"
    ATTRS{ltm_capable}=="no"
    ATTRS{speed}=="480"
    ATTRS{bMaxPacketSize0}=="64"
    ATTRS{bDeviceClass}=="09"
    ATTRS{configuration}==""
    ATTRS{busnum}=="3"

  looking at parent device '/devices/platform/soc/1c1b000.usb':
    KERNELS=="1c1b000.usb"
    SUBSYSTEMS=="platform"
    DRIVERS=="ehci-platform"
    ATTRS{companion}==""
    ATTRS{uframe_periodic_max}=="100"
    ATTRS{driver_override}=="(null)"

  looking at parent device '/devices/platform/soc':
    KERNELS=="soc"
    SUBSYSTEMS=="platform"
    DRIVERS==""
    ATTRS{driver_override}=="(null)"

  looking at parent device '/devices/platform':
    KERNELS=="platform"
    SUBSYSTEMS==""
    DRIVERS==""
```

**Comment by sgiannulli** [comment]
I prefer go on here so you can track the process; I have applied the latest version in this PR; now the disk list is correct but mounting the hard drives ended with a lot of errors: Maybe caused by the database in omv is now corrupted or full of lost links.
I hope to have time tomorrow evening to start with a fresh install.
immagine
immagine

**Comment by votdev** [comment]
> I prefer go on here so you can track the process; I have applied the latest version in this PR; now the disk list is correct but mounting the hard drives ended with a lot of errors: Maybe caused by the database in omv is now corrupted or full of lost links.

Yes, i think that's the case.

> The errors are in syslog, nothing in the webui when I try to mount a disk, even the apply button does not show.
> 
> ```
> Nov  9 23:44:36 localhost monit[1753]: 'filesystem_srv_dev-disk-by-id-usb-USB-WD-WCASYF842922-0-0' unable to read filesystem '/srv/dev-disk-by-id-usb-USB-WD-WCASYF842922-0-0' state
> Nov  9 23:44:36 localhost monit[1753]: 'filesystem_srv_dev-disk-by-id-usb-USB-WD-WCASYF842922-0-0' trying to restart
> Nov  9 23:44:36 localhost monit[1753]: 'mountpoint_srv_dev-disk-by-id-usb-USB-WD-WCASYF842922-0-0' status failed (1) -- /srv/dev-disk-by-id-usb-USB-WD-WCASYF842922-0-0 is not a mountpoint
> Nov  9 23:44:36 localhost monit[1753]: Filesystem '/srv/dev-disk-by-id-usb-USB-WD-WCASYF844062-0-0' not mounted
> Nov  9 23:44:36 localhost monit[1753]: 'filesystem_srv_dev-disk-by-id-usb-USB-WD-WCASYF844062-0-0' unable to read filesystem '/srv/dev-disk-by-id-usb-USB-WD-WCASYF844062-0-0' state
> Nov  9 23:44:36 localhost monit[1753]: 'filesystem_srv_dev-disk-by-id-usb-USB-WD-WCASYF844062-0-0' trying to restart
> Nov  9 23:44:36 localhost monit[1753]: 'mountpoint_srv_dev-disk-by-id-usb-USB-WD-WCASYF844062-0-0' status failed (1) -- /srv/dev-disk-by-id-usb-USB-WD-WCASYF844062-0-0 is not a mountpoint
> Nov  9 23:44:36 localhost monit[1753]: Filesystem '/srv/dev-disk-by-label-orangepi2' not mounted
> Nov  9 23:44:36 localhost monit[1753]: 'filesystem_srv_dev-disk-by-label-orangepi2' unable to read filesystem '/srv/dev-disk-by-label-orangepi2' state
> Nov  9 23:44:36 localhost monit[1753]: 'filesystem_srv_dev-disk-by-label-orangepi2' trying to restart
> Nov  9 23:44:36 localhost monit[1753]: 'mountpoint_srv_dev-disk-by-label-orangepi2' status failed (1) -- mountpoint: /srv/dev-disk-by-label-orangepi2: No such file or directory
> Nov  9 23:44:36 localhost monit[1753]: Filesystem '/srv/dev-disk-by-label-orangepi1' not mounted
> Nov  9 23:44:36 localhost monit[1753]: 'filesystem_srv_dev-disk-by-label-orangepi1' unable to read filesystem '/srv/dev-disk-by-label-orangepi1' state
> Nov  9 23:44:36 localhost monit[1753]: 'filesystem_srv_dev-disk-by-label-orangepi1' trying to restart
> Nov  9 23:44:36 localhost monit[1753]: 'mountpoint_srv_dev-disk-by-label-orangepi1' status failed (1) -- mountpoint: /srv/dev-disk-by-label-orangepi1: No such file or directory
> ```
> 
> I hope to have time tomorrow evening to start with a fresh install.
> immagine
> immagine

Thank you very much for testing.

**Comment by sgiannulli** [comment]
lashed omv 5.5.15 clean backup image
updated to 5.5.16 (only omv package)
`reboot`
changed 99-openmediavault-dev-disk-by-id.rules to this PR
`update-initramfs -u`
`reboot`
plugged the first hd: correctly showed in the webui, no errors in syslog
plugged the second hd: correctly showed in the webui, no errors in syslog
mounted the first hd: no errors in the webui, no errors in syslog, under `/srv` folder `dev-disk-by-label-orangepi1` is created
mounted the second hd: no errors in the webui, no errors in syslog, under `/srv` folder `dev-disk-by-label-orangepi2` is created
`reboot`
no errors in syslog, hd still correctly mounted and listed with their serial numbers

**Pull request merged**
