### PR TITLE
Allow proxying omv web-gui to folder by replacing absolute paths with relative

### PR DESCRIPTION
**Pull request by zguithues**
This pull request replaces 2 absolute paths with relative ones.  These changes allow me to proxy the omv web-gui to a folder (ie: mydomain.com/omv/)

I learned of the issue and how to fix here: https://forum.openmediavault.org/index.php/Thread/20857-OMV-Web-UI-Behind-NGINX-Config/

### CODE REVIEW

**Comment by votdev** [comment]
Please rebase your PR and sign the CLA.

**Comment by votdev** [comment]
Thanks for showing the problem. I've fixed that issue with commit https://github.com/openmediavault/openmediavault/commit/5fa5e12a92ae9ec46bd3ed7f0102df4e6d88f1f9 because this is the faster way because your PR missed the signed-by comment, was not squashed and not rebased.

**Comment by zguithues** [comment]
Thanks!  You rock!

**Comment by TitanSpirit** [comment]
OMV behind a reverse proxy based on NGINX in a Docker container is something that work, however 

omv.subdomain.conf
`server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name omv.*;

    include /config/nginx/ssl.conf;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";
    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_omv 192.168.80.49;
        proxy_max_temp_file_size 2048m;        
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto http;
        proxy_pass http://$upstream_omv:64005;
    }
}
`
It will provide wrong IP of the client without changes on OMV side. Is it possible to make it compatible, by default? OMV just seem to not handle properly X-Forwarded-For headers. 

[](https://stackoverflow.com/questions/64009526/pointing-nginx-reverse-proxy-back-to-host-instead-to-a-docker-container-and-gett)

**Pull request closed without merging**
