### PR TITLE
Upgrade to Salt 3005.1

### PR DESCRIPTION
**Pull request by votdev**
Signed-off-by: Volker Theile <votdev@gmx.de>

- [ ] References issue
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by votdev** [comment]
Waitng for https://github.com/saltstack/salt/issues/62334 ([PR](https://github.com/saltstack/salt/pull/62952))

**Comment by ryecoaaron** [comment]
@votdev It looks like error vs debug blocker was merged and 3005.1-2 was released a couple of weeks after that.

**Comment by votdev** [comment]
> @votdev It looks like error vs debug blocker was merged and 3005.1-2 was released a couple of weeks after that.

Sadly the [Debian packages](https://repo.saltproject.io/py3/debian/11/amd64/latest/) seem not to be updated till now.

**Comment by ryecoaaron** [comment]
Ah.  I didn't know they had a Debian repo and thought you were building the package from the source code release.

**Comment by votdev** [comment]
> @votdev It looks like error vs debug blocker was merged and 3005.1-2 was released a couple of weeks after that.

According to https://github.com/saltstack/salt/compare/v3005.1...v3005.1-3 i do not see any changes that will fix issue 62334.

**Comment by ryecoaaron** [comment]
Sorry, I thought it was fixed by https://github.com/saltstack/salt/pull/62952

**Pull request merged**
