### PR TITLE
Modify shared folder unit file

### PR DESCRIPTION
**Pull request by votdev**
Change the targets to ensure all filesystems are ready and up.

https://forum.openmediavault.org/index.php/Thread/28550-Shared-Folders/
https://forum.openmediavault.org/index.php/Thread/25042-MergerFS-folders-not-mounted-in-sharedfolders/

Signed-off-by: Volker Theile <votdev@gmx.de>

- [ ] References issue
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by ryecoaaron** [comment]
This will break sharedfolders on zfs.

**Comment by votdev** [comment]
> This will break sharedfolders on zfs.

I don't think so because ZFS things are done before ``local-fs.target``, see https://github.com/zfsonlinux/zfs/blob/master/etc/systemd/system/zfs-mount.service.in#L8. At ``sysinit.target`` everyting related to mounting should be done (according to https://www.freedesktop.org/software/systemd/man/bootup.html#System%20Manager%20Bootup).

**Comment by ryecoaaron** [comment]
> I don't think so because ZFS things are done before local-fs.target

They are supposed to be done before local-fs.target but they aren't.  Hopefully they are by the sysinit time frame.

I'm still not sure how this fixes the mount during apply though.  I understand it would fix the mount during boot issue.  I guess I will do some testing.

I know this is a different issue but this doesn't fix the remount triggered during sharedfolder creation that fails to restart a mount unit because the folder is in use.

**Comment by votdev** [comment]
> > I don't think so because ZFS things are done before local-fs.target
> 
> They are supposed to be done before local-fs.target but they aren't. Hopefully they are by the sysinit time frame.
> 

If not, then we can simply re-add the ``After=zfs-mount.service``line.

> I'm still not sure how this fixes the mount during apply though. I understand it would fix the mount during boot issue. I guess I will do some testing.
> 

It won't, but it will fix the booting issue. A small step forward.

**Comment by subzero79** [comment]
Another approach in my opinion could be use a custom target line up with graphical or multi-user. We know multi-user is the last one maybe omv could set the default sharedfolder.target doesn’t do any harm. 
Cons:could hurt cron scripts that are set with the @reboot instead of cron time

**Comment by votdev** [comment]
Should be finally fixed by f5e4d283eff11ab291e7fa0b5a4fd0aea2735d9d. It seems the order of the conditions was the key.

**Pull request merged**
