### PR TITLE
Refactor file system management.

### PR DESCRIPTION
**Pull request by votdev**
* /dev/disk/by-label filesystem device files are not supported anymore because they are not unique and predictable.
* Add 'comment' and 'usagewarnthreshold' to mountpoint datamodel.
* Try to auto-mount a filesystem if it is missing. Alert if the filesystem is still missing after a given time period.
* Adapt 'Storage | File Systems' pages.
* File system are not mounted immediately when they are added in the UI. They are mounted and can be used AFTER the configuration changes have been applied. This is the common workflow of the whole UI.

Filesystems itself can't be deleted anymore. If this is needed, the parent device can be wiped in the `Storage | Disks` page.

Bildschirmfoto vom 2021-04-03 13-51-00

Bildschirmfoto vom 2021-04-03 13-51-36

Bildschirmfoto vom 2021-04-03 13-53-14

Bildschirmfoto vom 2021-04-03 13-53-31

Signed-off-by: Volker Theile <votdev@gmx.de>

- [ ] References issue
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by votdev** [comment]
Is the `Delete` file system feature used by any plugin?

**Comment by ryecoaaron** [comment]
> Is the Delete file system feature used by any plugin?

I don't think so.

**Review by ryecoaaron — DISMISSED** [review]
Looks ok to me.  What happens if monit fails to mount a filesystem?

**Comment by votdev** [comment]
> Looks ok to me. What happens if monit fails to mount a filesystem?

If that happens, then no automatic solution will work IMO. But if it happens, a notification is send in any case, so the administrator is aware of and can take over.

**Comment by ryecoaaron** [comment]
> If that happens, then no automatic solution will work IMO. But if it happens, a notification is send in any case, so the administrator is aware of and can take over.

That works for me.

**Pull request merged**
