### PR TITLE
Fix monit/proftpd issue when implicit TLS is enabled.

### PR DESCRIPTION
**Pull request by votdev**
Signed-off-by: Volker Theile <votdev@gmx.de>

- [ ] References issue
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by votdev** [comment]
See https://forum.openmediavault.org/index.php?thread/32819-ftp-server-disconnects-during-upload/&postID=261774#post261774

**Comment by scar45** [comment]
Request to reopen this issue due to a problematic error that forces `monit` to restart `proftpd` every 30 seconds, disrupting the integrity of any transfers in progress. I have **Implicit SSL** _disabled_, as my particular FTP usage does not work with it enabled, and I am seeing this in the logs:

`monit[32082]: 'proftpd' failed protocol test [FTP] at [localhost]:21 [TCP/IP TLS] -- SSL connection error: error:1408F10B:SSL routines:ssl3_get_record:wrong version number`

I have a self-signed certificate that was generated in OMV applied to the FTP server, with the **TLS required** advanced option _enabled_. I found a similar [bug report on monit's issue tracker](https://bitbucket.org/tildeslash/monit/issues/944/dovecot-fails-imaps-check-on-ubuntu-2004), however it explains that a solution may be in v5.27+, whereas OMV uses v5.26 (this may be irrelevant, I'm not fully sure).

I tried modifying the generated **/etc/monit/conf.d/openmediavault-proftpd.conf** file to instead contain: 

`if failed port 21 protocol ftp with ssl options { selfsigned: allow } for 3 cycles then restart`

...but this failed to work and I still see the same error message as above in the logs. Could it be something related to SSLv3, as hinted by the log? I also tried to explicitly exclude SSLv3, but this is only supported in the newer monit version, v5.27+:

image

In the meantime, I've had to comment out the following line:

`#if failed port 21 protocol ftp with ssl for 3 cycles then restart`

...though this is not ideal of course. Hoping a solution can be found, thanks in advance.

**Comment by mod242** [comment]
I have the exact same Problem like @scar45. I have **Implicit SSL** _disabled_ but **TLS** _enabled_ which leads to the situation that monit is killing my ProFTPD instance every 30 seconds. 

I think it would be necessary to check whether implicit SSL is enabled or not to decide whether to check from monit "with ssl" or not.

**Comment by votdev** [comment]
> Request to reopen this issue due to a problematic error that forces `monit` to restart `proftpd` every 30 seconds, disrupting the integrity of any transfers in progress. I have **Implicit SSL** _disabled_, as my particular FTP usage does not work with it enabled, and I am seeing this in the logs:
> 
> `monit[32082]: 'proftpd' failed protocol test [FTP] at [localhost]:21 [TCP/IP TLS] -- SSL connection error: error:1408F10B:SSL routines:ssl3_get_record:wrong version number`
> 
> I have a self-signed certificate that was generated in OMV applied to the FTP server, with the **TLS required** advanced option _enabled_. I found a similar [bug report on monit's issue tracker](https://bitbucket.org/tildeslash/monit/issues/944/dovecot-fails-imaps-check-on-ubuntu-2004), however it explains that a solution may be in v5.27+, whereas OMV uses v5.26 (this may be irrelevant, I'm not fully sure).
> 
> I tried modifying the generated **/etc/monit/conf.d/openmediavault-proftpd.conf** file to instead contain:
> 
> `if failed port 21 protocol ftp with ssl options { selfsigned: allow } for 3 cycles then restart`
> 
> ...but this failed to work and I still see the same error message as above in the logs. Could it be something related to SSLv3, as hinted by the log? I also tried to explicitly exclude SSLv3, but this is only supported in the newer monit version, v5.27+:
> 
> image
> 
> In the meantime, I've had to comment out the following line:
> 
> `#if failed port 21 protocol ftp with ssl for 3 cycles then restart`
> 
> ...though this is not ideal of course. Hoping a solution can be found, thanks in advance.
> 
> **EDIT:** Wanted to add that ever since I updated OMV to 5.5.23-1 (verified by checking dates/logs), I have a flood of these types of messages in **/var/log/proftpd/tls.log**, that never appeared prior to the OMV update:
> 
> `mod_tls/2.7[7878]: SSL/TLS required but absent on control channel, denying ^V^C^A^A<86>^A command`
> 
> Hope this may offer some additional help/clues.

Updating to `monit 5.27.1` does not fix the issue, monit still fails with `monit[32082]: 'proftpd' failed protocol test [FTP] at [localhost]:21 [TCP/IP TLS] -- SSL connection error: error:1408F10B:SSL routines:ssl3_get_record:wrong version number`. I've tried every possible Monit configuration option to get it running. The issue is finally fixed by not using `protocol ftp` which let Monit do a default connection test which fulfills the requirements here. The issue is fixed by https://github.com/openmediavault/openmediavault/pull/955 in `openmediavault** 5.5.24`.

**Comment by Marsup** [comment]
Hi @votdev,

Do you plan to release 5.5.24 anytime soon ? Anything we can do to help ?

**Comment by votdev** [comment]
> Hi @votdev,
> 
> Do you plan to release 5.5.24 anytime soon ? Anything we can do to help ?

If you can't wait to get the package have a [look here](https://github.com/openmediavault/openmediavault/issues/959#issuecomment-774556028), otherwise please wait till next week.

**Pull request merged**
