### PR TITLE
Add plugin that enables the ability to create shared folders in…

### PR DESCRIPTION
**Pull request by votdev**
- Fix various issues.
- Add plugin that enables the ability to create shared folders in the root filesystem.

Signed-off-by: Volker Theile <votdev@gmx.de>

- [ ] References issue
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by soapee01** [comment]
Volker:

First: THANK YOU!

I tried to install it today via apt the web ui. First I started with apt update/upgrade

Here's what I'm seeing at the moment. Note: This is running as a LXC in proxmox.  The error message in the gui just keeps repeating until I hit close.

Should I try from source and compile instead?

```
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  openmediavault-sharerootfs
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 2724 B of archives.
After this operation, 15.4 kB of additional disk space will be used.
Get:1 http://packages.openmediavault.org/public usul/main amd64 openmediavault-sharerootfs all 5.0-1 [2724 B]
Fetched 2724 B in 1s (4210 B/s)
Selecting previously unselected package openmediavault-sharerootfs.
(Reading database ... (Reading database ... 5%(Reading database ... 10%(Reading database ... 15%(Reading database ... 20%(Reading database ... 25%(Reading database ... 30%(Reading database ... 35%(Reading database ... 40%(Reading database ... 45%(Reading database ... 50%(Reading database ... 55%(Reading database ... 60%(Reading database ... 65%(Reading database ... 70%(Reading database ... 75%(Reading database ... 80%(Reading database ... 85%(Reading database ... 90%(Reading database ... 95%(Reading database ... 100%(Reading database ... 42901 files and directories currently installed.)
Preparing to unpack .../openmediavault-sharerootfs_5.0-1_all.deb ...
Unpacking openmediavault-sharerootfs (5.0-1) ...
Setting up openmediavault-sharerootfs (5.0-1) ...
jq: error (at <stdin>:1): Cannot iterate over null (null)
dpkg: error processing package openmediavault-sharerootfs (--configure):
 installed openmediavault-sharerootfs package post-installation script subprocess returned error exit status 5
Errors were encountered while processing:
 openmediavault-sharerootfs

>>> *************** Error ***************

<<< *************************************'

```
These are the only relevant logs I found.
```
# tail /var/log/dpkg.log
2020-01-25 19:27:27 install openmediavault-sharerootfs:all <none> 5.0-1
2020-01-25 19:27:27 status half-installed openmediavault-sharerootfs:all 5.0-1
2020-01-25 19:27:27 status unpacked openmediavault-sharerootfs:all 5.0-1
2020-01-25 19:27:27 startup packages configure
2020-01-25 19:27:27 configure openmediavault-sharerootfs:all 5.0-1 <none>
2020-01-25 19:27:27 status unpacked openmediavault-sharerootfs:all 5.0-1
2020-01-25 19:27:27 status half-configured openmediavault-sharerootfs:all 5.0-1
2020-01-25 19:30:27 startup packages configure
2020-01-25 19:30:27 configure openmediavault-sharerootfs:all 5.0-1 <none>
2020-01-25 19:30:27 status half-configured openmediavault-sharerootfs:all 5.0-1
```

**Comment by soapee01** [comment]
The issue seems to be in openmediavault-sharerootfs.postinst

Specifically this line (copied from the :

```
omv# salt-call --local --retcode-passthrough --no-color --out=json mount.fstab
{
    "local": {}
}

```
I'm unfamiliar with SaltStack, but I'll dig some more on this.

It appears that this is tied to LXC not having fstab entries.

```
# /cat/etcfstab
# UNCONFIGURED FSTAB FOR BASE SYSTEM
```
I'll debug this some more with a full KVM installation.

**Comment by votdev** [comment]
The problem here is that OMV was never designed to work in a container environment. It needs to see real block devices to do some decisions during runtime.

**Comment by votdev** [comment]
It finally comes out that OMV requires a real filesystem while processing the shared folders. Because of that i had to undo previous changes in the `openmediavault-sharerootfs` plugin. See https://github.com/openmediavault/openmediavault/commit/edf113f551403cee7ef019640f3cb926eb51c42d.
The consequence of this is that if you want to run OMV in a container, there MUST be a filesystem visible to blkid for rootfs.

**Pull request merged**
