### PR TITLE
Switches must be interactive

### PR DESCRIPTION
**Pull request by R0maNNN**
Led must indicate.
Toggle button must be interactive.

### CODE REVIEW

**Comment by votdev** [comment]
Thanks for your contribution. I will not merge it right now because in my opinion the WebUI does not look as good as before. Your PR is correct because the switches indicate an interactive element which it is not, but the changed look isn't that good. I will think about what can be done to improve the look.

**Comment by votdev** [comment]
See http://bugtracker.openmediavault.org/view.php?id=1745.

**Comment by R0maNNN** [comment]
I think the true way is to make switches interactive. In case of impossibility of turning on the component without configuring, it must be gray.

switched on -> image

switched off -> image

switched off (need configuring) -> image

It looks like:
default

**Comment by R0maNNN** [comment]
@votdev 
please look at

**Comment by votdev** [comment]
Done by https://github.com/openmediavault/openmediavault/commit/81bbf607725b3a269e54fa4b2970f8f54a88a9e7.

**Pull request closed without merging**
