### PR TITLE
Issue 891 improve bug template

### PR DESCRIPTION
**Pull request by mi-hol**
[improve bug template]

Fixes: [#891]

Signed-off-by: mi-hol <22799428+mi-hol@users.noreply.github.com>

- [ x] References issue
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by mi-hol** [comment]
Squash can be applied with least effort using 'Squash & Merge" button here
image

**Review by votdev — APPROVED** [review]

**Comment by votdev** [comment]
@mi-hol The `Signed-off-by: mi-hol 22799428+mi-hol@users.noreply.github.com` must be included in the commit message, otherwise DCO will block the merge button.

**Comment by mi-hol** [comment]
when I try to resolve the DCO issue according to the commands provided in "Details"
new git errors appear.
No clue how to get this working

**Comment by mi-hol** [comment]
@votdev root cause of git error could have been a bug in version
after upgrade from "git v2.29.2.2" to Version 2.30.0 "rebase" command completed but now 
"git push" reports error

`PS Z:\openmediavault> git rebase --continue
[detached HEAD 05f63173a] Update issue templates
 Author: Volker Theile <votdev@gmx.de>
 2 files changed, 58 insertions(+)
 create mode 100644 .github/ISSUE_TEMPLATE/bug_report.md
 create mode 100644 .github/ISSUE_TEMPLATE/feature_request.md
dropping 6f4a58d240906515cc72bf7ebd5981a703aa689b Update issue templates -- patch contents already upstream
Successfully rebased and updated refs/heads/pr/892.
PS Z:\openmediavault> git push --force-with-lease origin issue_891_improve_bug_template
error: src refspec issue_891_improve_bug_template does not match any
error: failed to push some refs to 'https://github.com/openmediavault/openmediavault.git'
PS Z:\openmediavault>`

**Comment by votdev** [comment]
Please [Allow edits from maintainers](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to cleanup the PR. You can't do it yourself if you do not have much experience with git. I've done the changes already in a locale clone of your branch, but have no permission to push them. 
Another solution is to close this PR and start from scratch.

**Comment by votdev** [comment]
I'm wondering about commits like `Merge branch ...`. It's not necessary to merge a branch if you work on your PR branch. If you want to update it, you simply rebase it with `git rebase upstream/master`.

**Comment by mi-hol** [comment]
@votdev 
2021-01-05 11_30_25-Window

'Allow edits by maintainer' had already  been enabled since beginning.
Some bug in git/github seems to hit us here.
Would you mind to copy & publish the change under your account?

**Comment by votdev** [comment]
> Would you mind to copy & publish the change under your account?

Sure

**Comment by votdev** [comment]
Superseded by https://github.com/openmediavault/openmediavault/pull/916.

**Pull request closed without merging**
