### PR TITLE
Use gender-neutral language

### PR DESCRIPTION
**Pull request by Julian-O**
Particularly in the UI.

English text (only) changed, but it was a key into the translation files, so they were correspondingly updated.

My IDE automatically removes trailing blanks on lines of code, so a couple of those were corrected too.

(Confession: I don't have unit-tests configured locally. Relying on automated run.)

Fixes: #486

Signed-off-by: Julian-O <openmediavaultcorrespondence@somethinkodd.com>

- [X] References issue
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by votdev** [comment]
@Julian-O There is no need to modify the .po files, your changes will get lost when i rebuild the languages. You only need to modify the text in the .(inc|js|php|...) files. The .pot will be generated out of this sources, then uploaded to Transifex (https://translate.openmediavault.org), the translators update their language there, and a script will download this .po files into the project again.

**Comment by votdev** [comment]
Thx

**Comment by Julian-O** [comment]
Re: .po files

Ah, I understand now. Thanks. I was trying to avoid making extra work for each of the translators - I was worried they would need to restranslate the phrase when their old translation is probably perfectly fine, just because the key changed.

**Comment by votdev** [comment]
> Re: .po files
> 
> Ah, I understand now. Thanks. I was trying to avoid making extra work for each of the translators - I was worried they would need to restranslate the phrase when their old translation is probably perfectly fine, just because the key changed.

They need to do so, but the Transifex UI is intelligent enough to suggest the previous translation.

**Comment by ryecoaaron** [comment]
Quite a few non-english languages will not need to be translated since the current form is considered gender neutral.

**Pull request merged**
