### PR TITLE
Relocate the user management navigation menu

### PR DESCRIPTION
**Pull request by votdev**
navbar

Signed-off-by: Volker Theile <votdev@gmx.de>

- [ ] References issue
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by votdev** [comment]
Which position of the `User Management` menu is the best from the end-user point of view? Which position will help to minimize problems for them.

Please start a discussion here.

**Comment by PrplHaz4** [comment]
Makes sense at the bottom for me since I consider it the last step of setting things up.

**Comment by ryecoaaron** [comment]
Seems fine to me.  What about changing it to just "Users" to make the side bar narrower?  Management is implied in most of the other sections.

**Comment by flmaxey** [comment]
As previously note in a PM:
If **User Management** is in the middle of the absolute bare minimum of configuration and services required to setup a working NAS (with open permissions), it becomes a temptation to new users.  (What does this do...?)  I like the idea of getting new users started without incident.  

I believe moving **User Management** down the list would have at least a small damping effect on new users opening it to see what's there and "clicking on boxes".  Once OMV is up and running, I believe the average user would be reluctant to tamper with a working NAS or, at least, they'll understand the effects of indiscriminate tampering.

Where advanced and expert users are concerned, it really doesn't matter where the menu item is located.  They'll recognize it and use it as needed.

**Pull request merged**
