### PR TITLE
Replace custom cursors with system provided alternatives

### PR DESCRIPTION
**Pull request by SkaceKamen**
Replaces custom cursor images with cursors provided by the browser. The custom icons don't scale well for non-standard DPI. Also the waiting icon has incorrect aspect-ratio and is very pixelated. And I think using OS provided cursors is better user experience.

Removed icons:
image
image

Replaced with (rendered on Windows 10):
image
image

### CODE REVIEW

**Comment by ryecoaaron** [comment]
The cursors are like that on purpose.  They are a tribute to the Amiga.  Pretty sure Volker does not want to change them.

**Comment by votdev** [comment]
The cursors will not be changed because this is a tribute to the Amiga computer.

**Comment by SkaceKamen** [comment]
Ok, sorry, I thought it was leftover from something. Just a question, is the 503 error screen also a tribute? It seems a bit out of a place design-wise.

**Comment by votdev** [comment]
> Ok, sorry, I thought it was leftover from something. Just a question, is the 503 error screen also a tribute? It seems a bit out of a place design-wise.

Yes, see https://en.wikipedia.org/wiki/Guru_Meditation

**Pull request closed without merging**
