### PR TITLE
Use the unattended-upgrades package instead on cron-apt

### PR DESCRIPTION
**Pull request by votdev**
Fixes: https://github.com/openmediavault/openmediavault/issues/1652

### CODE REVIEW

**Comment by ryecoaaron** [comment]
You might want to look at setting Unattended-Upgrade::Allowed-Origins

**Comment by votdev** [comment]
> You might want to look at setting Unattended-Upgrade::Allowed-Origins

I can not find that entry in /etc/apt/apt.conf.d/50unattended-upgrades. Is this still available in Bookwork? What do you suggest to set there?

**Comment by votdev** [comment]
I just want to auto-install security updates only.

**Comment by ryecoaaron** [comment]
Then you would just want:
Unattended-Upgrade::Allowed-Origins {
"${distro_id}:${distro_codename}-security";
};

**Pull request merged**
