### PR TITLE
Change absolute asset paths in workbench to relative

### PR DESCRIPTION
**Pull request by EmTeedee**
Changes absolute asset paths in workbench to relative. Almost all other paths are already relative.

Fixes: #1516 

Signed-off-by: Tobias Tiederle <git.emteedee@das-komitee.de>

- [x] References issue
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by votdev** [comment]
Can you confirm that this is working in your setup?

**Comment by EmTeedee** [comment]
Sorry, I had problems setting up the build environment.
I see the same issue, working on resolving it.

I've changed the paths in the compiled webpack and it's working, just need to get the sass compiler to output the same.

I'll tag you again when I get that working.

**Comment by votdev** [comment]
Have you ever checked how the paths are looking after this PR has been applied. Some are in the root like `/foo.svg`, others look like `./assets/images/bar.gif`. This does not really look like a valid improvement, this is IMO spaghetti code. I am sorry, but i can not approve and merge it this way.

**Review by votdev — CHANGES_REQUESTED** [review]
The PR needs an overall refactoring to do not result in spaghetti code where some images are located in the root, others are still in `/assets/xxx`.

**Comment by EmTeedee** [comment]
Thanks for fixing the relative path issue.

I stayed away from the `^` because of this comment from the angular project:
>  [...] paths starting with ^ is a Webpack specific feature and as such we don't provide support nor guarantee that these will continue to work in the future.
https://github.com/angular/angular-cli/issues/18013#issuecomment-649373940

Either way, it works and when it stops they hopefully provide a supported way of achieving the same, angular/scss just doesn't at the moment.

**Comment by votdev** [comment]
> I stayed away from the `^` because of this comment from the angular project:

There is no alternative to that right at the moment. At least i do not know about or have found any.

**Pull request closed without merging**
