### PR TITLE
Fix translation

### PR DESCRIPTION
**Pull request by MountainWang**
Fix translation

Fix template varible name which shouldn't translate

Signed-off-by: Mountain Wang <pps.qing@gmail.com>

### CODE REVIEW

**Comment by votdev** [comment]
Thanks for the fixes. Could you please create an account on Transifex and do the changes at [translate.openmediavault.org](https://translate.openmediavault.org)?

**Comment by MountainWang** [comment]
Of course, please approve my join request on Transifex.

**Comment by votdev** [comment]
> Of course, please approve my join request on Transifex.

Done

**Comment by votdev** [comment]
I'm closing this issue in favour of doing it the regular way by fixing the translations on Transifex.

**Pull request closed without merging**
